version: '3.8'
services:
  server:
    image: ghcr.io/geniusyield/dex-contracts-api:latest
    container_name: server
    environment:
      CORE_MAESTRO_API_KEY: ${CORE_MAESTRO_API_KEY}
      MAESTRO_API_KEY: ${MAESTRO_API_KEY}
      SERVER_API_KEY: ${SERVER_API_KEY}
      SERVER_CONFIG: |
        coreProvider:
          maestroToken: <<CORE_MAESTRO_API_KEY>>
          turboSubmit: false
        networkId: "mainnet" # supported: mainnet ot preprod
        logging:
          - type: {tag: stderr}
            severity: "Debug" # Options: Debug, Info, Warning or Error
            verbosity: V2 # Options: `V0`, `V1`, `V2`, `V3` and `V4` (See katip docs for details)
        port: 8082
        maestroToken: <<MAESTRO_API_KEY>>
        serverApiKey: <<SERVER_API_KEY>>
    restart: always
